CREATE TABLE Generals
(
	[ModuleID] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100) NOT NULL,
	[DescriptionHeader] NVARCHAR(MAX) NOT NULL,
	[DescriptionBody] NVARCHAR(MAX) NOT NULL,
	[Category] NVARCHAR(50) NOT NULL,
	[Img1] NVARCHAR(250) NOT NULL,
	[Img2] NVARCHAR(250) NOT NULL,
	[Img3] NVARCHAR(250) NOT NULL,
	[Img4] NVARCHAR(250) NOT NULL,
	[Img5] NVARCHAR(250) NOT NULL,
	[Img6] NVARCHAR(250) NOT NULL,
	[video] NVARCHAR(250) NULL,
	[Data] datetime2 not null DEFAULT GETDATE()
)